---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-webcam
spec:
  containers:
    - name: alpine
      image: localhost:32000/webcam:alpine
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: webcam
          mountPath: /dev/video0
      securityContext:
        privileged: true
  nodeSelector:
    webcam: "true"
  volumes:
    - name: webcam
      hostPath:
        path: /dev/video0
        type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-webcam-service
spec:
  type: NodePort
  selector:
    app: alpine-webcam
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

