---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sample-picam-alpine-ds
spec:
  selector:
    matchLabels:
      app: sample-picam-alpine
  template:
    metadata:
      labels:
        app: sample-picam-alpine
    spec:
      containers:
        - name: alpine-picam
          image: localhost:32000/webcam
          command:
            - /mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer
            - -i
            - "/mjpg-streamer/mjpg-streamer-experimental/input_uvc.so -d /dev/video0"
            - -o
            - "/mjpg-streamer/mjpg-streamer-experimental/output_http.so -p 8080 -w /mjpg-streamer/mjpg-streamer-experimental/www"
            #- sleep
            #- infinity
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: picam
              mountPath: /dev/video0
          securityContext:
            privileged: true
      nodeSelector:
        picam: "true"
      volumes:
        - name: picam
          hostPath:
            path: /dev/video0
            type: CharDevice
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-picam-service
spec:
  type: NodePort
  selector:
    app: sample-picam-alpine
  ports:
    - port: 8080

