---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sample-picam-ubuntu-ds
spec:
  selector:
    matchLabels:
      app: sample-picam-ubuntu
  template:
    metadata:
      labels:
        app: sample-picam-ubuntu
    spec:
      containers:
        - name: ubuntu-picam
          image: localhost:32000/webcam:ubuntu
          command:
            - sleep
            - infinity
            #- /mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer
            #- -i
            #- "/mjpg-streamer/mjpg-streamer-experimental/input_uvc.so -yuv"
            #- -o
            #- "/mjpg-streamer/mjpg-streamer-experimental/output_http.so -p 8080 -w /mjpg-streamer/mjpg-streamer-experimental/www"
            #- sleep
            #- infinity
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: picam
              mountPath: /dev/video0
          securityContext:
            privileged: true
      nodeSelector:
        picam: "true"
      volumes:
        - name: picam
          hostPath:
            path: /dev/video0
            type: CharDevice
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-picam-service
spec:
  type: NodePort
  selector:
    app: sample-picam-ubuntu
  ports:
    - port: 8080

